spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parvezi9ahmad/configuration_properties
          clone-on-start: true
management:
  security:
    enabled: false
